dbfilename redis_queue.rdb
dir /home/admin/Documents/nesa_projects/erpnext-vms-system/vms-system/config/pids
pidfile /home/admin/Documents/nesa_projects/erpnext-vms-system/vms-system/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/admin/Documents/nesa_projects/erpnext-vms-system/vms-system/config/redis_queue.acl
